# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thamiressite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(max_length=9),
        ),
    ]
